const VOCAB_CATEGORIES = {
  it: {
    label: 'IT',
    terms: [
      ["hardware", "matériel"],
      ["software", "logiciel"],
      ["desktop computer", "ordi de bureau"],
      ["laptop", "ordi portable"],
      ["peripheral", "périphérique"],
      ["device", "un appareil"],
      ["keyboard", "clavier"],
      ["key", "une touche"],
      ["touchpad", "pavé tactile"],
      ["arrow (cursor)", "flèche"],
      ["to display", "afficher"],
      ["display / screen", "un écran"],
      ["screen", "un écran"],
      ["screenshot", "capture d'écran"],
      ["mouse", "souris"],
      ["scroll wheel", "molette de défilement"],
      ["cursor", "curseur"],
      ["pointer", "curseur"],
      ["motherboard", "carte-mère"],
      ["CPU / processor", "processeur"],
      ["hard disk drive", "disque dur"],
      ["hard drive", "disque dur"],
      ["storage", "stockage"],
      ["SSD disk", "disque SSD"],
      ["power supply", "alimentation électrique"],
      ["power cable", "cordon d'alimentation"],
      ["power plug", "fiche d'alimentation"],
      ["graphics card / GPU", "carte graphique (CG)"],
      ["to heat up", "chauffer"],
      ["to cool down", "refroidir"],
      ["cooling vent", "trou d'aération"],
      ["to browse", "naviguer / parcourir"],
      ["browser", "un navigateur"],
      ["wire", "fil métallique, fil élec"],
      ["wireless", "sans-fil"],
      ["fan", "ventilateur"],
      ["to tinker with", "bidouiller, bricoler"],
      ["to fiddle with", "bidouiller, bricoler"],
      ["to build from scratch", "créer de toutes pièces"],
      ["earphones / earbuds", "écouteurs"],
      ["headphones / headset", "casque"],
      ["data", "données"],
      ["database", "base de données"],
      ["data recovery", "récupération de données"],
      ["folder", "dossier"],
      ["file", "fichier"],
      ["word processor", "traitement de texte"],
      ["spreadsheet", "tableur"],
      ["to save (as)", "enregistrer"],
      ["to backup", "sauvegarder"],
      ["to type / to input", "saisir"],
      ["to delete", "supprimer"],
      ["to update / update", "mettre à jour / mise à jour"],
      ["up-to-date", "à jour"],
      ["to log in", "se connecter"],
      ["username", "nom d'utilisateur"],
      ["search engine", "moteur de recherche"],
      ["home page", "page d'accueil"],
      ["to sign up / register", "s'inscrire"],
      ["to subscribe", "s'abonner"],
      ["to report", "signaler"],
      ["to download", "télécharger"],
      ["to upload", "téléverser"],
      ["to run", "exécuter"],
      ["to run on (e.g. Linux)", "fonctionner sous"],
      ["OS / operating system", "système d'exploitation"],
      ["to supply", "fournir"],
      ["to seek", "chercher"],
      ["to research", "faire de la recherche"],
      ["to look for", "chercher"]
    ]
  },
  general: {
    label: 'Général',
    terms: [
      ["reliable", "fiable"],
      ["to supply", "fournir"],
      ["to search", "fouiller"],
      ["to research", "chercher"],
      ["to look for", "chercher"],
      ["to seek", "chercher"],
      ["to sort out", "trier"],
      ["household", "foyer"],
      ["instead of", "au lieu de"],
      ["as well as", "ainsi que"],
      ["feature", "fonctionnalité"],
      ["factory", "usine"],
      ["brand", "marque"],
      ["companies", "entreprises"],
      ["society", "la société"],
      ["business", "entreprise"],
      ["firm", "entreprise"],
      ["accountant", "comptable"],
      ["ships", "expédie"],
      ["advertise", "promouvoir"],
      ["IT", "information technology"],
      ["bills", "additions"],
      ["invoice", "facture"],
      ["to train", "former"],
      ["training", "formation"],
      ["to run something", "gérer"],
      ["subsidiary", "filiale"],
      ["to go bankrupt", "faire faillite"],
      ["stock market", "la bourse"],
      ["shareholder", "actionnaire"],
      ["liability", "responsabilité"],
      ["shop", "magasin"],
      ["outlet", "magasin"],
      ["store", "magasin"],
      ["suppliers", "fournisseurs"],
      ["sales representative", "commercial"]
    ]
  }
};
